common_args:
  training_type: "simulation"                   # 训练类型,不用改
  random_seed: 45                                # 随机种子
#  available_memory: 8

data_args:
  dataset: "femnist"                              # 数据集
  data_cache_dir: ~\.cache\fedml_data\fed_emnist            # 数据集缓存路径
  partition_method: "hetero"                    # 数据集划分方式
  partition_alpha: 0.8                          # 数据集划分比例

model_args:
  model: "cnn" #lr                               # 模型

train_args:                                     # 训练参数
  federated_optimizer: "FedAvg"                 # DecentralizedFL   FedAvg   HierarchicalFL  FedAvg_seq
  client_id_list: "[]"                          # 客户端id列表
  client_num_in_total: 10                    # 客户端总数
  client_num_per_round: 10                    # 每轮参与训练的客户端数量
  comm_round: 15                                  # 通信轮数
  epochs: 100                                    # 客户端每次训练的轮数
  batch_size: 64                                # 客户端每次训练的batch_size
  client_optimizer: sgd                         # 客户端优化器
  learning_rate: 0.001                           # 学习率
  weight_decay: 0.001                           # 权重衰减
  stage: train


validation_args:                                # 验证集参数
  frequency_of_the_test: 5                      # 每训练几轮进行一次测试

device_args:                                    # 设备参数
  using_gpu: true
  gpu_id: 0
  device_type: "gpu"
  process_id: 0

comm_args:
  backend: "sp"                                 # 通信方式Single-Process simulation

attack_args:                                    # 攻击参数
  enable_attack: false                          # 是否启用攻击
  attack_type: "Byzantine_attack"                             # 攻击类型
  attack_rate: 0.1                             # 攻击比率
  attack_intensity: 10                           # 攻击强度(缩放攻击)

defense_args:                                   # 防御参数
  enable_defense: false                         # 是否启用防御
  defense_type: "DWAMA"              # 防御类型 norm_diff_clipping norm_clipping norm_clipping_with_truncation norm_clipping_with_truncation_and_noise,,MahalnobisDefense
  is_defense: 1

# krum防御参数
krum:
    krum_rate: 0.4

# norm_diff_clipping防御参数
norm_diff_clipping:
  norm_bound: 1.0


# ****************************************************************************************
tracking_args:
  enable_tracking: false                        # 是否启用tracking
  # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  # 用wandb (Weight and Biases)记录日志 https://wandb.ai/site https://docs.wandb.ai/
  enable_wandb: false                            # 是否启用wandb
  wandb_key: 453fd07189d1af4dfffdd69a491ebdd7ce60fb00  # 个人的wandb key
  wandb_entity: hsenn                       # 个人的wandb entity
  wandb_project: MyExperiment                    # 个人的wandb project
  run_name: Defense_0.05_5_darts                 # 个人的wandb run_name
  using_mlops: false                            # 是否启用mlops



