common_args:
  training_type: "simulation"
  random_seed: 69
  available_memory: 8

data_args:
  dataset: "PAMAP2"
  partition_method: "hetero"
  partition_alpha: 0.8

model_args:
  model: "LSTM_PAMAP2" #lr                    

train_args:
  federated_optimizer: "CMetaFL"
  client_id_list: "[1,2,3,4,5,6,7,8,9,10]"
  client_num_in_total: 10
  client_num_per_round: 10
  comm_round: 15
#  epochs: 100
  adaptation_steps: 5
  batch_size: 32
  client_optimizer: sgd
  learning_rate: 0.001
  weight_decay: 0.001
  stage: train
  # 元学习训练参数
  meta_learning_rate: 0.01

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: true
  gpu_id: 0
  device_type: "gpu"
  process_id: 0

comm_args:
  backend: "sp"

# ****************************************************************************************
tracking_args:
  enable_tracking: false
  # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key:
  wandb_entity:
  run_name:
  using_mlops: false



